### ISSUE TITLE
Matrix3::inverse is wrong, mixed up with adjugate?

### ISSUE THREAD

**Issue by dvtomas** [samiBendou/geomath#1]
```rust
let m = Matrix3::from_translation(&vector::vec2(1.0, 2.0));
println!("{:?}\n {:?}\n {:?}", m, m * m.inverse(), m * m.adjugate());
```

gives 

```
( 1.000  0.000  1.000 )
( 0.000  1.000  2.000 )
( 0.000  0.000  1.000 )
 
( 0.000  -2.000  2.000 )
( -2.000  -3.000  4.000 )
( -1.000  -2.000  1.000 )
 
( 1.000  0.000  0.000 )
( 0.000  1.000  0.000 )
( 0.000  0.000  1.000 )
```

The fact that `m * m.inverse() =/= identity`, but `m * m.adjugate() == identity` is very strange to me, although I'm no expert on linear algebra. Shouldn't it be the other way around? But how could such a fundamental error make it to production? I'm confused.

**Comment by samiBendou** [comment]
Hello dvtomas, thanks for your feedback !

In the case of the `m` matrix you instantiated, inverse and adjugate are the same so it is true that `m * m.adjugate() == identity` but it is rather strange that  `m * m.inverse() != identity`. 

I am currently investigating on the reasons why this is happening.

**Comment by samiBendou** [comment]
@dvtomas please download the latest version of the crate (0.2.4) the issue should be fixed
